name: mana-food-project-services

services:

  db-mana-food-product:
    container_name: manafood-product-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: db_manafood_product
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psenha123" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app-mana-food-product:
    container_name: manafood-product-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db-mana-food-product:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mana-food-product:3306/db_manafood_product?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_FLYWAY_ENABLED: "true"

volumes:
  mysql_data: